version: "3.9"

services:
  redis_server:
    container_name: redis_server
    image: redis:latest
  app:
    container_name: app
    image: golang:1.22
    command: go run server.go
    volumes:
      - ./src:/go/src
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    links:
      - redis_server
    depends_on:
      - redis_server